import type { Database } from 'better-sqlite3';

/**
 * Bump whenever the DDL below changes shape. `migrate` drops and recreates the
 * schema on mismatch rather than writing ALTER migrations: the database is a
 * derived cache of the source tree, never user data, so a rebuild is always
 * cheaper and safer than a migration path we'd have to keep correct forever.
 */
export const SCHEMA_VERSION = 4;

/**
 * Identifies the parse/extract logic that produced the cached per-file partials in
 * `files.partial`. A file's content hash tells us the *input* is unchanged; this
 * tells us the *code that processed it* is unchanged too.
 *
 * BUMP THIS whenever extraction output changes — new tree-sitter queries, a new
 * symbol kind, a changed id scheme, an extractor bug fix. Forgetting to means users
 * keep serving partials produced by the old logic until the file happens to change.
 * A schema bump also invalidates the cache, so this only needs bumping for changes
 * that leave the schema alone.
 */
export const PIPELINE_VERSION = 3;

/**
 * Substring matching (CandidateDiscovery's "name contains token") has no usable
 * B-tree index — `LIKE '%tok%'` degrades to a full scan. FTS5's trigram tokenizer
 * is built for exactly this and is the reason discovery can stop walking in-memory
 * Maps.
 *
 * Measured on a synthetic 400k-symbol corpus with selective tokens:
 *   JS Map scan (the old path)   190.60 ms
 *   LIKE on the base table       316.26 ms
 *   trigram MATCH                  2.34 ms
 *
 * Caveat: trigram indexes only substrings of 3+ characters. Shorter tokens must
 * fall back to a base-table LIKE — see MIN_TRIGRAM_LENGTH.
 *
 * Note the index is *external content* (`content='symbols'`). An earlier version
 * stored its own copy keyed by the TEXT symbol id, which made every hit a
 * string-keyed lookup back into `symbols` — and that join, not the matching,
 * dominated. Measured at 100k symbols on a token matching 12% of the corpus:
 *   own content, join on TEXT id    150.40 ms   (13.64 MB index)
 *   external content, join on rowid  79.53 ms   ( 5.11 MB index)
 * Selective tokens are ~1 ms either way, so external content is strictly better.
 */
export const MIN_TRIGRAM_LENGTH = 3;

/**
 * WAL lets the visualizer/MCP read while the watcher writes a rebuild.
 * synchronous=NORMAL trades fsync-per-commit for speed — acceptable because a
 * torn database after a crash is regenerated by the next build.
 */
const PRAGMAS = `
  PRAGMA journal_mode = WAL;
  PRAGMA synchronous = NORMAL;
  PRAGMA foreign_keys = OFF;
  PRAGMA temp_store = MEMORY;
`;

/**
 * Ranges are flattened to four INTEGER columns rather than a JSON blob. The BFS
 * and materializer paths touch ranges constantly, and parsing JSON per row there
 * dominated everything else. It also makes the derived scope-membership rule from
 * semantic-model/types.ts ("Symbol.range inside Scope.range") a SQL predicate.
 *
 * `metadata` stays JSON TEXT: the type is an open Record<string, unknown> by
 * design, so normalizing it into columns would break that contract.
 */
const DDL = `
  CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT
  );

  /*
   * One row per source file. The partial column holds the gzipped JSON of that
   * file's PartialSemanticModel — the output of parse+extract, which is the
   * expensive stage. Keyed by content_hash so an unchanged file skips to merge.
   *
   * Stored as an opaque blob rather than reconstructed from the normalized tables
   * because a partial contains things those tables do not: every reference
   * candidate (not just the unresolved ones) and localTypeBindings, which are
   * resolver-only plumbing and never enter the graph.
   */
  CREATE TABLE IF NOT EXISTS files (
    path         TEXT PRIMARY KEY,
    language     TEXT,
    content_hash TEXT,
    mtime_ms     INTEGER,
    indexed_at   TEXT,
    partial      BLOB
  );

  CREATE TABLE IF NOT EXISTS symbols (
    id                   TEXT PRIMARY KEY,
    kind                 TEXT NOT NULL,
    name                 TEXT NOT NULL,
    name_lower           TEXT NOT NULL,
    qualified_name       TEXT NOT NULL,
    qualified_name_lower TEXT NOT NULL,
    file_path            TEXT NOT NULL,
    file_path_lower      TEXT NOT NULL,
    start_line           INTEGER NOT NULL,
    start_col            INTEGER NOT NULL,
    end_line             INTEGER NOT NULL,
    end_col              INTEGER NOT NULL,
    exported             INTEGER NOT NULL,
    visibility           TEXT NOT NULL,
    metadata             TEXT NOT NULL,
    is_project           INTEGER NOT NULL DEFAULT 0
  );

  /*
   * Trigram index over the three fields discovery matches substrings against.
   * External content: the rows live in the symbols table and are joined back on
   * integer rowid, so nothing is duplicated and the join is an integer-PK seek.
   * Column names must match symbols for the 'rebuild' command to populate it.
   */
  CREATE VIRTUAL TABLE IF NOT EXISTS symbols_fts USING fts5(
    name_lower,
    qualified_name_lower,
    file_path_lower,
    content='symbols',
    content_rowid='rowid',
    tokenize='trigram'
  );

  CREATE TABLE IF NOT EXISTS scopes (
    id              TEXT PRIMARY KEY,
    kind            TEXT NOT NULL,
    parent_scope_id TEXT,
    owner_symbol_id TEXT,
    file_path       TEXT NOT NULL,
    start_line      INTEGER NOT NULL,
    start_col       INTEGER NOT NULL,
    end_line        INTEGER NOT NULL,
    end_col         INTEGER NOT NULL,
    metadata        TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS containments (
    parent_id TEXT NOT NULL,
    child_id  TEXT NOT NULL,
    kind      TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS resolved_references (
    candidate_id      TEXT PRIMARY KEY,
    from_symbol_id    TEXT NOT NULL,
    to_symbol_id      TEXT NOT NULL,
    kind              TEXT NOT NULL,
    resolution_method TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS unresolved_references (
    id              TEXT PRIMARY KEY,
    from_symbol_id  TEXT NOT NULL,
    kind            TEXT NOT NULL,
    raw_name        TEXT NOT NULL,
    qualifier_chain TEXT NOT NULL,
    import_path     TEXT,
    ast_node_type   TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    start_line      INTEGER NOT NULL,
    start_col       INTEGER NOT NULL,
    end_line        INTEGER NOT NULL,
    end_col         INTEGER NOT NULL,
    metadata        TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS diagnostics (
    seq                 INTEGER PRIMARY KEY AUTOINCREMENT,
    kind                TEXT NOT NULL,
    severity            TEXT NOT NULL,
    message             TEXT NOT NULL,
    file_path           TEXT NOT NULL,
    start_line          INTEGER,
    start_col           INTEGER,
    end_line            INTEGER,
    end_col             INTEGER,
    related_symbol_ids  TEXT,
    related_candidate_id TEXT
  );
`;

/**
 * Every index here backs a specific hot query:
 *  - name_lower / qualified_name_lower: CandidateDiscovery's exact + substring matching,
 *    which currently walks every entry of an in-memory Map per query token.
 *  - file_path: byFile grouping and per-file invalidation.
 *  - containments(parent_id|child_id) and resolved_references(from|to): the edge
 *    lookups behind getEdgesFrom/getEdgesTo, i.e. every BFS step.
 *  - resolved_references(to_symbol_id, kind): makes getCallersOf an index seek
 *    instead of scanning all incoming edges and filtering by kind in JS.
 */
const INDEXES = `
  CREATE INDEX IF NOT EXISTS idx_symbols_name_lower  ON symbols(name_lower);
  CREATE INDEX IF NOT EXISTS idx_symbols_qname_lower ON symbols(qualified_name_lower);
  CREATE INDEX IF NOT EXISTS idx_symbols_file        ON symbols(file_path);
  CREATE INDEX IF NOT EXISTS idx_symbols_file_lower  ON symbols(file_path_lower);
  CREATE INDEX IF NOT EXISTS idx_symbols_kind        ON symbols(kind);

  CREATE INDEX IF NOT EXISTS idx_scopes_file         ON scopes(file_path);
  CREATE INDEX IF NOT EXISTS idx_scopes_owner        ON scopes(owner_symbol_id);

  CREATE INDEX IF NOT EXISTS idx_cont_parent         ON containments(parent_id);
  CREATE INDEX IF NOT EXISTS idx_cont_child          ON containments(child_id);

  CREATE INDEX IF NOT EXISTS idx_rref_from           ON resolved_references(from_symbol_id);
  CREATE INDEX IF NOT EXISTS idx_rref_to             ON resolved_references(to_symbol_id);
  CREATE INDEX IF NOT EXISTS idx_rref_to_kind        ON resolved_references(to_symbol_id, kind);
  CREATE INDEX IF NOT EXISTS idx_rref_from_kind      ON resolved_references(from_symbol_id, kind);

  CREATE INDEX IF NOT EXISTS idx_uref_from           ON unresolved_references(from_symbol_id);
  CREATE INDEX IF NOT EXISTS idx_uref_file           ON unresolved_references(file_path);

  CREATE INDEX IF NOT EXISTS idx_diag_file           ON diagnostics(file_path);
`;

const ALL_TABLES = [
  'meta',
  'files',
  'symbols_fts',
  'symbols',
  'scopes',
  'containments',
  'resolved_references',
  'unresolved_references',
  'diagnostics'
];

function readSchemaVersion(db: Database): number | null {
  // The meta table itself may not exist yet on a fresh or foreign file.
  const hasMeta = db
    .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name='meta'`)
    .get();
  if (!hasMeta) return null;

  const row = db.prepare(`SELECT value FROM meta WHERE key = 'schema_version'`).get() as
    | { value: string }
    | undefined;
  if (!row) return null;

  const parsed = Number.parseInt(row.value, 10);
  return Number.isNaN(parsed) ? null : parsed;
}

function dropAll(db: Database): void {
  for (const table of ALL_TABLES) {
    db.exec(`DROP TABLE IF EXISTS ${table};`);
  }
}

/**
 * Brings the database to SCHEMA_VERSION, recreating it from scratch if what's on
 * disk was written by a different version. Safe to call on every open.
 */
export function migrate(db: Database): void {
  db.exec(PRAGMAS);

  const current = readSchemaVersion(db);
  if (current !== null && current !== SCHEMA_VERSION) {
    dropAll(db);
  }

  db.exec(DDL);
  db.exec(INDEXES);

  db.prepare(
    `INSERT INTO meta (key, value) VALUES ('schema_version', ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`
  ).run(String(SCHEMA_VERSION));
}
